# Generated by Django 3.2.9 on 2023-03-15 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travelcode', models.CharField(max_length=10)),
                ('cost', models.CharField(max_length=10)),
                ('paid', models.CharField(max_length=10)),
                ('is_halfpaid', models.BooleanField(default=False)),
                ('is_fullpaid', models.BooleanField(default=False)),
                ('is_finish', models.BooleanField(default=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=255)),
                ('phoneno', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='img/companyimage/%y%mm/%dd')),
                ('companyaddress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncludePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placename', models.CharField(max_length=255)),
                ('hotels', models.CharField(default='No Hotel', max_length=255, null=True)),
                ('lengthofstay', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='img/includeplace/%y%mm/%dd')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='img/place/%y/%mm/%dd')),
                ('cost', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('people_limit', models.IntegerField(default=10)),
                ('travel_sdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SenderName', models.CharField(max_length=255)),
                ('SenderPhoneno', models.CharField(max_length=11)),
                ('ReceiverName', models.CharField(max_length=255)),
                ('ReceiverPhoneno', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phoneno', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255, null=True)),
                ('idcardno', models.CharField(max_length=22, null=True)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='OtherIncome',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='products',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='user',
        ),
        migrations.RemoveField(
            model_name='soldproduct',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneno',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.DeleteModel(
            name='SoldProduct',
        ),
        migrations.AddField(
            model_name='paymentinformation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='includeplace',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='includeplace', to='app.package'),
        ),
        migrations.AddField(
            model_name='includeplace',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app.package'),
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mbooking', to='app.package'),
        ),
        migrations.AddField(
            model_name='booking',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='app.traveler'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
