# Generated by Django 3.2.9 on 2023-03-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230315_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReceiverName', models.CharField(max_length=255)),
                ('ReceiverPhoneno', models.CharField(max_length=25)),
                ('SenderName', models.CharField(max_length=255)),
                ('SenderPhoneno', models.CharField(max_length=255)),
                ('Amount', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='discount',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='PaymentInformation',
        ),
    ]
