# Generated by Django 3.2.9 on 2023-01-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
