# Generated by Django 4.1.5 on 2023-01-29 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_traveler_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='travel_rdate',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='travel_sdate',
        ),
        migrations.AddField(
            model_name='package',
            name='people_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='package',
            name='travel_sdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
