# Generated by Django 3.2.9 on 2023-03-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='Operator',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
